name: biotine_image
path:
data_shape: [3, 128, 128]
transforms:
  _target_: torchvision.transforms.transforms.Compose
  transforms:
  - _target_: torchvision.transforms.Normalize
    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]
  - _target_: torchvision.transforms.transforms.Resize
    size: 128
selected_dists: [1, 5, 10, 15, 19] # [1, 5, 10, 15, 19] OR list(range(1, 20))
